<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTsxtpyn\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTsxtpyn/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTsxtpyn.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTsxtpyn\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerTsxtpyn\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Tsxtpyn',
    'container.build_id' => '7eeafb35',
    'container.build_time' => 1530270599,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTsxtpyn');
